name: user_interface
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  convex_bottom_bar: ^3.2.0
  get: 4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  geolocator: ^11.0.0
  flutter: 
    sdk: flutter
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  date_time_format: ^2.0.1
  html: ^0.15.0
  timeago: ^3.3.0
  flutter_html: 3.0.0-beta.2
  flutter_layout_grid: ^1.0.6
  flutter_math_fork: ^0.6.1


dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/LoginLogo.png
    - assets/images/AppBar.png
    - assets/images/absensi.png
    - assets/images/class.png
    - assets/images/roster.png
    - assets/images/pengumuman.png
    - assets/images/guru.png
    - assets/images/tanyajawab.png
    - assets/images/ChangePassword.png
    - assets/images/contohgambar.png

  uses-material-design: true
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-VariableFont_wdth,wght.ttf
